portofolio/urls.py
from django.urls import path
from . import views

app_name = 'portofolio'

urlpatterns = [
    path('', views.launch, name='launch'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('experiences/', views.experiences, name='experiences'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portofolio.urls')),
]

portofolio/models.py
from django.db import models

# Create your models here.

portofolio/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def launch(request):
    return render(request, 'launch.html')

def about(request):
    return render(request, 'about.html')

def skills(request):
    return render(request, 'skills.html')

def experiences(request):
    return render(request, 'experiences.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

portofolio/templates/about.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>

	<body>
		<!-- ABOUT PAGE -->
		<div class="about-page" id="ap">
			<h2>Tentang</h2>

			<p class="tentang-saya">
			 	Rifqi adalah mahasiswa Ilmu Komputer di Fasilkom UI. <br>
				Di tahun kedua perkuliahannya, pemuda yang aktif, energik, dan ceria ini <br>
				sangat senang mempelajari mata perancangan pemrograman web.
			</p>

			<h2>Pendidikan</h2>

			<div class="pendidikan-saya">
				<div class="instansi">
					<img src="{% static 'images/edu/logo_sma6.png' %}" class="logo-instansi">
					<h4>SMA Negeri 6 Bogor</h4>
				</div>

				<div class="instansi">
					<img src="{% static 'images/edu/logo_ui.png' %}" class="logo-instansi">
					<h4>Universitas Indonesia</h4>
				</div>	
			</div>

		</div>
	</body>

portofolio/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>
	
	<!-- CONTACT PAGE -->
	<body>
		<div class="hubungi-saya" id="cp">
			<h3>Hubungi Saya</h3>
			<div class="contact-container">
				<a href="mailto:mqnisen@gmail.com" target="_blank"><img src="{% static 'images/contact/logo_email.png' %}" class="logo-cp"/></a>
				<a href="https://www.linkedin.com/in/mrifqi" target="_blank"><img src="{% static 'images/contact/logo_linkedin.png' %}" class="logo-cp"/></a>
				<a href="http://line.me/ti/p/mqnisen" target="_blank"><img src="{% static 'images/contact/logo_line.png' %}" class="logo-cp"/></a>
				<a href="https://www.instagram.com/enbeqi" target="_blank"><img src="{% static 'images/contact/logo_ig.png' %}" class="logo-cp"/></a>
			</div>
			<a href="{% url 'portofolio:launch' %}"><img src="{% static 'images/iconfinder_upbutton.png' %}" class="scroll-btn"/></a>
		</div>
		
	</body>

portofolio/templates/experiences.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>

	<body>
		<!-- EXPERIENCES PAGE -->
		<div class="pengalaman-saya" id="exp">
			<h3>Organisasi</h3>
			<div class="exp-box">
				<img src="{% static 'images/exp/logo_bem.png' %}" class=logo-exp>
				<div class="exp-text">
					<h5>BEM FASILKOM UI 2019</h5>
					<h6>Dept. Akademis dan Kepemimpinan</h6>
				</div>
			</div>

			<h3 class="vol-header">Kepanitiaan</h3>
			<div class="vol-container">
				<div class="exp-box">
					<img src="{% static 'images/exp/logo_cf.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>COMPFEST 11</h5>
						<h6>Staff Playground</h6>
					</div>
				</div>

				<div class="exp-box">
					<img src="{% static 'images/exp/logo_cgt.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>Computers Get Together</h5>
						<h6>Staff Bazaar dan Konsumsi</h6>
					</div>
				</div>

				<div class="exp-box">
					<img src="{% static 'images/exp/logo_siwak.png' %}" class=logo-exp>
					<div class="exp-text">
						<h5>SIWAK-NG</h5>
						<h6>Staff Akomodasi</h6>
					</div>
				</div>

			</div>
		</div>
	</body>

portofolio/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>

	<body>
		<!-- GALLERY PAGE -->
		<div class="galeri-saya" id="gs">
			
			<div class="photos-container">
				<div class="right-container">
					<img src="{% static 'images/gallery/gf1-1.jpg' %}">
					<img src="{% static 'images/gallery/gf1-2.jpg' %}">
					<img src="{% static 'images/gallery/gf1-3.jpg' %}">
					<img src="{% static 'images/gallery/gf1-4.jpg' %}">
				</div>
				<div class="left-container">
					<img src="{% static 'images/gallery/gf2-1.jpg' %}">
					<img src="{% static 'images/gallery/gf2-2.jpg' %}">
					<img src="{% static 'images/gallery/gf2-3.jpg' %}">
					<img src="{% static 'images/gallery/gf2-4.jpg' %}">
				</div>
				<div class="right-container">
					<img src="{% static 'images/gallery/gf3-1.jpg' %}">
					<img src="{% static 'images/gallery/gf3-2.jpg' %}">
					<img src="{% static 'images/gallery/gf3-3.jpg' %}">
					<img src="{% static 'images/gallery/gf3-4.jpg' %}">
				</div>
			</div>
		</div>
		
	</body>

portofolio/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<body>
    <h1>Hello My Name is {{ name }}</h1>
</body>
</html>

portofolio/templates/launch.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>


	<body>

		<!-- LAUNCH PAGE -->
		<div class="launch-page" id="lp">
			<img src="{% static 'images/profile/foto-b.png' %}" class="foto-saya">
			<p>Muhammad Rifqi</p>
			<a href="{% url 'portofolio:about' %}"><img src="{% static 'images/iconfinder_downbutton.png' %}" class="scroll-btn"/></a>

		</div>

	</body>

portofolio/templates/skills.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>Story-3 Rifqi</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css"  href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
</head>



	<nav class="navbar navbar-expand-lg warnaNavbar navbar-expand" id="nb">
  		<a class="navbar-brand" href="{% url 'portofolio:launch' %}">Portofolio</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	    	<div class="navbar-nav ml-auto">
	      		<a class="nav-item nav-link" href="{% url 'portofolio:about' %}">Tentang</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:skills' %}">Kemampuan</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:experiences' %}">Pengalaman</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:gallery' %}">Galeri</a>
	      		<a class="nav-item nav-link" href="{% url 'portofolio:contact' %}">Hubungi</a>
	    	</div>
  		</div>
	</nav>

	<body>
<!-- SKILLS PAGE -->
		<div class="kemampuan-saya" id="skl">
			<h2>Kemampuan</h2>

			<div class="skill-container">
				<div class="skill">
					<h5 class="name">python</h5>
					<img src="{% static 'images/skills/logo_python.png' %}" class=logo-skill>
					<h5>7/10</h5>
				</div>

				<div class="skill">
					<h5 class="name">java</h5>
					<img src="{% static 'images/skills/logo_java.png' %}" class=logo-skill>
					<h5>8/10</h5>
				</div>

				<div class="skill">
					<h5 class="name">html-css</h5>
					<img src="{% static 'images/skills/logo_html-css.png' %}" class=logo-skill>
					<h5>7/10</h5>
				</div>
			</div>
		</div>
	</body>